FROM public.ecr.aws/lambda/provided:al2

# Copy custom runtime bootstrap
COPY ./art.kittencat.lambda.lambdaruntime ${LAMBDA_RUNTIME_DIR}/bootstrap

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "function.handler" ]
